const studyBankHistory = [
    { q: "In what year did the First World War begin?", a: ["1912", "1914", "1916", "1918"], correct: "1914", explanation: "WWI began in 1914 following the assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo on June 28th." },
    { q: "Which empire was ruled by Suleiman the Magnificent at its peak?", a: ["Mongol Empire", "Ottoman Empire", "Persian Empire", "Byzantine Empire"], correct: "Ottoman Empire", explanation: "Suleiman I ruled the Ottoman Empire from 1520 to 1566, during which it reached its greatest territorial and cultural height." },
    { q: "The Magna Carta was signed in which year?", a: ["1066", "1215", "1348", "1492"], correct: "1215", explanation: "King John of England signed the Magna Carta in 1215, establishing for the first time that the king was subject to the rule of law." },
    { q: "What event triggered the start of the French Revolution?", a: ["The execution of Louis XVI", "The storming of the Bastille", "The signing of the Declaration of Rights", "Napoleon's coup"], correct: "The storming of the Bastille", explanation: "The storming of the Bastille prison on July 14, 1789 is considered the symbolic start of the French Revolution." },
    { q: "The Berlin Wall fell in which year?", a: ["1985", "1987", "1989", "1991"], correct: "1989", explanation: "The Berlin Wall fell on November 9, 1989, marking a pivotal moment in the end of the Cold War and the reunification of Germany." },
    { q: "Which country was the first to grant women the right to vote nationally?", a: ["United States", "United Kingdom", "New Zealand", "Sweden"], correct: "New Zealand", explanation: "New Zealand became the first self-governing country to grant women the right to vote in national elections in 1893." },
    { q: "The Treaty of Westphalia in 1648 ended which major conflict?", a: ["The Hundred Years' War", "The Thirty Years' War", "The Wars of the Roses", "The Crusades"], correct: "The Thirty Years' War", explanation: "The Peace of Westphalia ended the devastating Thirty Years' War and is considered a foundational moment in the development of modern state sovereignty." },
    { q: "Who led the Cuban Revolution that brought him to power in 1959?", a: ["Che Guevara", "Fidel Castro", "Fulgencio Batista", "Raúl Castro"], correct: "Fidel Castro", explanation: "Fidel Castro led the revolutionary movement that overthrew the Batista government and took control of Cuba in January 1959." },
    { q: "The Meiji Restoration of 1868 modernized which country?", a: ["China", "Korea", "Japan", "Vietnam"], correct: "Japan", explanation: "The Meiji Restoration returned power to the Japanese emperor and triggered rapid modernization and industrialization of Japan." },
    { q: "Which civilization built the city of Tenochtitlan, now modern-day Mexico City?", a: ["Maya", "Olmec", "Inca", "Aztec"], correct: "Aztec", explanation: "The Aztec Empire founded Tenochtitlan in 1325 on an island in Lake Texcoco. It became one of the largest cities in the world before Spanish conquest." }
];
