const studyBankVocabulary = [
    { q: "What does 'Ephemeral' mean?", a: ["Lasting forever", "Lasting a very short time", "Deeply rooted", "Widely known"], correct: "Lasting a very short time", explanation: "Ephemeral describes something that is short-lived or transitory. From the Greek 'ephemeros' meaning 'lasting a day'." },
    { q: "What does 'Laconic' mean?", a: ["Talkative and expressive", "Using very few words", "Overly emotional", "Prone to exaggeration"], correct: "Using very few words", explanation: "Laconic means brief and concise. It comes from Laconia (Sparta), whose inhabitants were famous for their terse speech." },
    { q: "What does 'Sycophant' mean?", a: ["A harsh critic", "A creative thinker", "A person who flatters to gain favor", "A person who works alone"], correct: "A person who flatters to gain favor", explanation: "A sycophant is an obsequious flatterer who uses insincere praise to gain advantage with those in power." },
    { q: "What does 'Perfidious' mean?", a: ["Honest and reliable", "Treacherous and disloyal", "Overly cautious", "Thoroughly prepared"], correct: "Treacherous and disloyal", explanation: "Perfidious means guilty of betrayal or deceit. From the Latin 'perfidia' meaning faithlessness." },
    { q: "What does 'Ubiquitous' mean?", a: ["Rare and hard to find", "Present everywhere at once", "Unique to one place", "Ancient in origin"], correct: "Present everywhere at once", explanation: "Ubiquitous describes something that seems to appear everywhere simultaneously. From the Latin 'ubique' meaning 'everywhere'." },
    { q: "What does 'Enervate' mean?", a: ["To energize", "To weaken or drain of vitality", "To sharpen mentally", "To motivate strongly"], correct: "To weaken or drain of vitality", explanation: "Enervate means to cause someone to feel drained of energy or vitality — essentially the opposite of energize, despite the similar sound." },
    { q: "What does 'Equivocate' mean?", a: ["To speak clearly and directly", "To use ambiguous language to avoid commitment", "To argue logically", "To agree fully"], correct: "To use ambiguous language to avoid commitment", explanation: "Equivocate means to use vague or ambiguous language intentionally to mislead or avoid a definitive answer." },
    { q: "What does 'Mellifluous' mean?", a: ["Harsh and grating", "Sweet or musical in sound", "Bittersweet in taste", "Slow and deliberate"], correct: "Sweet or musical in sound", explanation: "Mellifluous describes a sound that is smooth and pleasant to hear. From Latin 'mel' (honey) and 'fluere' (to flow)." },
    { q: "What does 'Pernicious' mean?", a: ["Mildly annoying", "Gradually harmful in a subtle way", "Visibly destructive", "Beneficial in disguise"], correct: "Gradually harmful in a subtle way", explanation: "Pernicious describes something that causes harm in a way that is not immediately obvious. Often used for slowly damaging influences." },
    { q: "What does 'Magnanimous' mean?", a: ["Greedy and self-serving", "Generous and forgiving, especially to rivals", "Quick to anger", "Highly intelligent"], correct: "Generous and forgiving, especially to rivals", explanation: "Magnanimous describes a person who is noble-minded and generous in spirit, particularly toward opponents or those who have wronged them." }
];
